### ISSUE TITLE
Articulation draw is not idempotent

### ISSUE THREAD

**Issue by jaredjj3** [vexflow/vexflow#254]
I need to call `draw()` on an `Articulation` multiple times. However I get a different bounding box each time I call it. I believe it's due to the `setOrigin()` calls here because when I patch `setOrigin`, I get a consistent result: https://github.com/vexflow/vexflow/blob/d602715b1c05e21d3498f78b8b5904cb47ad3795/src/articulation.ts#L352-L364

**Comment by rvilarl** [comment]
@jaredjj3 this should be fixed in the vexflow 5.0.0-beta.1

**Comment by jaredjj3** [comment]
@rvilarl I'll remove the hack in https://github.com/stringsync/vexml/pull/275. Rendering performance has improved by _up to_ 30%!

**Comment by jaredjj3** [comment]
@rvilarl, would you reopen this issue please? I don't have the permission to.

`Articulation` drawing is still not idempotent. I'm still not getting a consistent result when calling `draw()` multiple times. If I call `reset()` in between `draw()`, it works as expected.

However, I was **not** able to reproduce this in a [JSFiddle](https://jsfiddle.net/087wekqd/4/) (I double checked the vexflow version).

Example 1:

before 5.0.0-beta.1, diff, after

![Image](https://github.com/user-attachments/assets/db060bce-d6c3-43fc-bd0a-6ed645d9faa5)

Example 2:

before, diff, after

![Image](https://github.com/user-attachments/assets/d5b60bcc-61b7-410b-9ca3-5dfbbe5276eb)
